# planning group names
arm_group_name: "panda_arm"
eef_name: "hand"
hand_name: "hand"
hand_frame: "panda_link8"
number_of_plans: 10

# Poses
open_gripper_pose: "open"
close_gripper_pose: "close"
home_pose: "ready"

# surface
table_refrence_frame: "world"
object_refrence_frame: "table"
surface_link: "table"
world_frame: "world"

# collision object
# CYLINDER object specifications
object_name: "object"
object_height: 0.25
object_radius: 0.02
object_pos_x: 0.0
object_pos_y: 0.0

table_name: "table"
table_height: 0.1
table_width: 0.5
table_length: 0.4
table_pos_x: 0.5
table_pos_y: -0.25

# gripper grasp frame transform
grasp_offset_x: 0.1 # X
grasp_offset_y: 0.0 # Y
grasp_offset_z: 0.0 # Z
grasp_rotation_x: 0.75 # rotation X axis
grasp_rotation_y: 1.5 # rotation Y axis

# place pose metrics (x/y position on table_top)
place_pos_x: 0.1
place_pos_y: 0.1
place_surface_offset: 0.0001 # place offset from table

# valid distance range when approaching an object for picking
approach_object_min_dist: 0.1
approach_object_max_dist: 0.15

# valid height range when lifting an object after pick
lift_object_min_dist: 0.01
lift_object_max_dist: 0.1
